name: Node.js CI
env:
  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

on:
  repository_dispatch:
  watch:
    types: [started]
    branches: [master]
  pull_request:
    branches: [ master ]
    types: [opened, reopened]  

jobs:
  test:

    runs-on: ubuntu-latest
    container: node:12

#    strategy:
#      matrix:
#        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v1
#      with:
#        node-version: ${{ matrix.node-version }}
    - run: npm install -g mocha 
    - run: npm install rewire 
    - run: npm install @schedulemaker/bannerjs --registry https://npm.pkg.github.com
    - run: mocha
      env:
        CI: true
